var searchData=
[
  ['d_20advanced_20performance_20requirements_20optional_20strong_0',['&lt;strong&gt;D Advanced Performance Requirements (Optional)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md94',1,'']]],
  ['de_20componentes_20físicos_1',['4. Patrones Template y Factory Method - Extensibilidad de Componentes Físicos',['../md_planning_2design-pattern.html#autotoc_md39',1,'']]],
  ['de_20contribuciones_2',['Tipos de Contribuciones',['../md_CONTRIBUTING.html#autotoc_md13',1,'']]],
  ['de_20coulomb_3',['4. Potencial Central (Interacción de Coulomb)',['../md_planning_2problems-to-solve.html#autotoc_md77',1,'']]],
  ['de_20dirac_5fsolver_4',['Diagramas UML para la Arquitectura de dirac_solver',['../md_planning_2ulm-diagrams.html',1,'']]],
  ['de_20diseño_20de_20dirac_5fsolver_5',['Arquitectura y Patrones de Diseño de dirac_solver',['../md_planning_2design-pattern.html',1,'']]],
  ['de_20entrada_6',['de entrada',['../md_planning_2problems-to-solve.html#autotoc_md79',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md69',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md74',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md84',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md64',1,'Parámetros de Entrada']]],
  ['de_20errores_20bugs_20y_20sugerencias_7',['Reporte de Errores (Bugs) y Sugerencias',['../md_CONTRIBUTING.html#autotoc_md14',1,'']]],
  ['de_20funcionalidades_8',['7. Patrón Decorator – Extensión Dinámica de Funcionalidades',['../md_planning_2design-pattern.html#autotoc_md44',1,'']]],
  ['de_20i_20o_9',['6. Patrón Facade - Interfaz Simplificada de I/O',['../md_planning_2design-pattern.html#autotoc_md43',1,'']]],
  ['de_20la_20base_10',['Espinores de la Base',['../md_planning_2spinor-definition.html#autotoc_md104',1,'']]],
  ['de_20la_20ecuación_20de_20dirac_11',['de la ecuación de dirac',['../index.html',1,'Dirac-Solver: Solucionador numérico de la Ecuación de Dirac.'],['../md_planning_2problems-to-solve.html',1,'Plan del Proyecto para un Solucionador de la Ecuación de Dirac']]],
  ['de_20la_20librería_20dirac_20solver_12',['Actualización de la librería Dirac Solver',['../md_planning_2Actualizaci_xC3_xB3n__constants.html',1,'']]],
  ['de_20la_20simulación_13',['2. Patrón Builder - Configuración de la Simulación',['../md_planning_2design-pattern.html#autotoc_md34',1,'']]],
  ['de_20los_20ángulos_14',['Definiciones de los Ángulos',['../md_planning_2spinor-definition.html#autotoc_md105',1,'']]],
  ['de_20pauli_20general_15',['Construcción del Espinor de Pauli General',['../md_planning_2spinor-definition.html',1,'']]],
  ['de_20potencial_20infinito_16',['2. Pozo de Potencial Infinito',['../md_planning_2problems-to-solve.html#autotoc_md67',1,'']]],
  ['de_20tt_20constants_20py_20tt_17',['1. Eliminación de &lt;tt&gt;constants.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md27',1,'']]],
  ['de_20uso_18',['Ejemplo de uso',['../classAbsorbingBoundary.html#autotoc_md19',1,'']]],
  ['de_20yukawa_19',['5. Potencial de Yukawa',['../md_planning_2problems-to-solve.html#autotoc_md82',1,'']]],
  ['dec_20',['DEC',['../CMakeCXXCompilerId_8cpp.html#ad1280362da42492bbc11aa78cbf776ad',1,'CMakeCXXCompilerId.cpp']]],
  ['decorator_21',['decorator',['../md_planning_2design-pattern.html#autotoc_md56',1,'6. Decorator'],['../md_planning_2ulm-diagrams.html#autotoc_md141',1,'6. Patrón Decorator']]],
  ['decorator_20–_20extensión_20dinámica_20de_20funcionalidades_22',['7. Patrón Decorator – Extensión Dinámica de Funcionalidades',['../md_planning_2design-pattern.html#autotoc_md44',1,'']]],
  ['definiciones_20de_20los_20ángulos_23',['Definiciones de los Ángulos',['../md_planning_2spinor-definition.html#autotoc_md105',1,'']]],
  ['definiciones_20físicas_24',['2. &lt;tt&gt;physics/&lt;/tt&gt; – Definiciones físicas',['../md_planning_2structure.html#autotoc_md121',1,'']]],
  ['definidas_20en_20tt_20_5f_5finit_5f_5f_20py_20tt_25',['2. Nuevas constantes globales definidas en &lt;tt&gt;__init__.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md28',1,'']]],
  ['del_20espinor_20de_20pauli_20general_26',['Construcción del Espinor de Pauli General',['../md_planning_2spinor-definition.html',1,'']]],
  ['del_20problema_27',['del problema',['../md_planning_2problems-to-solve.html#autotoc_md68',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md83',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md78',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md73',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md63',1,'Descripción del Problema']]],
  ['del_20proyecto_28',['Raíz del Proyecto',['../md_planning_2structure.html#autotoc_md117',1,'']]],
  ['del_20proyecto_20dirac_5fsolver_29',['Estructura del Proyecto dirac_solver',['../md_planning_2structure.html',1,'']]],
  ['del_20proyecto_20para_20un_20solucionador_20de_20la_20ecuación_20de_20dirac_30',['Plan del Proyecto para un Solucionador de la Ecuación de Dirac',['../md_planning_2problems-to-solve.html',1,'']]],
  ['descartadas_31',['10. Alternativas Consideradas y Descartadas',['../md_planning_2design-pattern.html#autotoc_md50',1,'']]],
  ['descripción_20del_20problema_32',['descripción del problema',['../md_planning_2problems-to-solve.html#autotoc_md83',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md78',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md73',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md68',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md63',1,'Descripción del Problema']]],
  ['design_2dpattern_2emd_33',['design-pattern.md',['../design-pattern_8md.html',1,'']]],
  ['diagramas_20uml_20para_20la_20arquitectura_20de_20dirac_5fsolver_34',['Diagramas UML para la Arquitectura de dirac_solver',['../md_planning_2ulm-diagrams.html',1,'']]],
  ['dim_35',['dim',['../classdirac__solver_1_1geometry_1_1Grid.html#a015c3ec7ba74fddfa326bde8a1b27cb6',1,'dirac_solver::geometry::Grid']]],
  ['dinámica_20de_20funcionalidades_36',['7. Patrón Decorator – Extensión Dinámica de Funcionalidades',['../md_planning_2design-pattern.html#autotoc_md44',1,'']]],
  ['dirac_37',['dirac',['../namespaceDirac.html',1,'Dirac'],['../md_planning_2problems-to-solve.html',1,'Plan del Proyecto para un Solucionador de la Ecuación de Dirac']]],
  ['dirac_20equation_20solver_38',['Presentation Structure: Requirements Engineering for a Dirac Equation Solver',['../md_planning_2requirements-engineering.html',1,'']]],
  ['dirac_20solver_39',['dirac solver',['../md_planning_2Actualizaci_xC3_xB3n__constants.html',1,'Actualización de la librería Dirac Solver'],['../md_CONTRIBUTING.html',1,'Cómo Contribuir a Dirac-Solver']]],
  ['dirac_20solver_3a_20solucionador_20numérico_20de_20la_20ecuación_20de_20dirac_40',['Dirac-Solver: Solucionador numérico de la Ecuación de Dirac.',['../index.html',1,'']]],
  ['dirac_5fsolver_41',['dirac_solver',['../md_planning_2design-pattern.html',1,'Arquitectura y Patrones de Diseño de dirac_solver'],['../md_planning_2ulm-diagrams.html',1,'Diagramas UML para la Arquitectura de dirac_solver'],['../namespacedirac__solver.html',1,'dirac_solver'],['../md_planning_2structure.html',1,'Estructura del Proyecto dirac_solver']]],
  ['dirac_5fsolver_20tt_42',['&lt;tt&gt;src/dirac_solver/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md119',1,'']]],
  ['dirac_5fsolver_3a_3acore_43',['core',['../namespacedirac__solver_1_1core.html',1,'dirac_solver']]],
  ['dirac_5fsolver_3a_3ageometry_44',['geometry',['../namespacedirac__solver_1_1geometry.html',1,'dirac_solver']]],
  ['dirac_5fsolver_3a_3ainitial_5fstate_45',['initial_state',['../namespacedirac__solver_1_1initial__state.html',1,'dirac_solver']]],
  ['dirac_5fsolver_3a_3astorage_46',['storage',['../namespacedirac__solver_1_1storage.html',1,'dirac_solver']]],
  ['diracmatrices_2eh_47',['diracmatrices.h',['../cpp__src_2DiracMatrices_8h.html',1,'(Espacio de nombres global)'],['../dirac__solver_2DiracMatrices_8h.html',1,'(Espacio de nombres global)']]],
  ['diracproblembuilder_48',['DiracProblemBuilder',['../classdirac__solver_1_1core_1_1DiracProblemBuilder.html',1,'dirac_solver::core']]],
  ['diracsolver_49',['DiracSolver',['../classdirac__solver_1_1core_1_1DiracSolver.html',1,'dirac_solver::core']]],
  ['diseño_20de_20dirac_5fsolver_50',['Arquitectura y Patrones de Diseño de dirac_solver',['../md_planning_2design-pattern.html',1,'']]],
  ['do_20em_20strong_51',['&lt;strong&gt;2. Functional Requirements (What the System &lt;em&gt;Must Do&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md90',1,'']]],
  ['docs_20tt_52',['&lt;tt&gt;docs/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md133',1,'']]],
  ['documentación_53',['Documentación',['../index.html#autotoc_md146',1,'']]],
  ['dominios_54',['4. &lt;tt&gt;geometry/&lt;/tt&gt; – Geometrías y dominios',['../md_planning_2structure.html#autotoc_md123',1,'']]],
  ['dv_55',['dv',['../classdirac__solver_1_1geometry_1_1Grid.html#aa826a5837f24f73bb7ab5675cfdf34da',1,'dirac_solver::geometry::Grid']]]
];
