var searchData=
[
  ['a_20dirac_20equation_20solver_0',['Presentation Structure: Requirements Engineering for a Dirac Equation Solver',['../md_planning_2requirements-engineering.html',1,'']]],
  ['a_20dirac_20solver_1',['Cómo Contribuir a Dirac-Solver',['../md_CONTRIBUTING.html',1,'']]],
  ['a_20physics_20engine_20core_20the_20c_20backend_20strong_2',['&lt;strong&gt;A. Physics Engine Core (The C++ Backend)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md91',1,'']]],
  ['a_20trozos_20efecto_20klein_3',['3. Potencial a Trozos (Efecto Klein)',['../md_planning_2problems-to-solve.html#autotoc_md72',1,'']]],
  ['absorbingboundary_4',['absorbingboundary',['../classAbsorbingBoundary.html#afa1eb9ef1855a32e0e9ab87e5082346e',1,'AbsorbingBoundary::AbsorbingBoundary()'],['../classAbsorbingBoundary.html',1,'AbsorbingBoundary']]],
  ['absorbingboundary_2eh_5',['AbsorbingBoundary.h',['../AbsorbingBoundary_8h.html',1,'']]],
  ['actualización_20de_20la_20librería_20dirac_20solver_6',['Actualización de la librería Dirac Solver',['../md_planning_2Actualizaci_xC3_xB3n__constants.html',1,'']]],
  ['actualización_5fconstants_2emd_7',['Actualización_constants.md',['../Actualizaci_xC3_xB3n__constants_8md.html',1,'']]],
  ['adapter_8',['adapter',['../md_planning_2design-pattern.html#autotoc_md57',1,'7. Adapter'],['../md_planning_2ulm-diagrams.html#autotoc_md143',1,'7. Patrón Adapter']]],
  ['adapter_20–_20interoperabilidad_20con_20librerías_20externas_9',['8. Patrón Adapter – Interoperabilidad con Librerías Externas',['../md_planning_2design-pattern.html#autotoc_md46',1,'']]],
  ['advanced_20performance_20requirements_20optional_20strong_10',['&lt;strong&gt;D Advanced Performance Requirements (Optional)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md94',1,'']]],
  ['al_20patrón_20builder_11',['API fluida gracias al Patrón Builder',['../md_planning_2design-pattern.html#autotoc_md35',1,'']]],
  ['algoritmos_12',['3. Patrón Strategy - Flexibilidad en los Algoritmos',['../md_planning_2design-pattern.html#autotoc_md37',1,'']]],
  ['alpha_5fx_13',['alpha_x',['../namespaceDirac.html#a220c778fcf6de926d905379ca36d7b81',1,'Dirac']]],
  ['alpha_5fy_14',['alpha_y',['../namespaceDirac.html#a1ee219a1bed9ad5012b3ef6ba2f5e381',1,'Dirac']]],
  ['alpha_5fz_15',['alpha_z',['../namespaceDirac.html#a21dac9d07b94f2221878134ce3951549',1,'Dirac']]],
  ['alternativas_20consideradas_20y_20descartadas_16',['10. Alternativas Consideradas y Descartadas',['../md_planning_2design-pattern.html#autotoc_md50',1,'']]],
  ['análisis_17',['7. &lt;tt&gt;visualization/&lt;/tt&gt; – Gráficos y análisis',['../md_planning_2structure.html#autotoc_md126',1,'']]],
  ['analysis_20what_20the_20system_20em_20must_20produce_20em_20strong_18',['&lt;strong&gt;C. Outputs and Analysis (What the System &lt;em&gt;Must Produce&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md93',1,'']]],
  ['and_20analysis_20what_20the_20system_20em_20must_20produce_20em_20strong_19',['&lt;strong&gt;C. Outputs and Analysis (What the System &lt;em&gt;Must Produce&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md93',1,'']]],
  ['api_20fluida_20gracias_20al_20patrón_20builder_20',['API fluida gracias al Patrón Builder',['../md_planning_2design-pattern.html#autotoc_md35',1,'']]],
  ['api_20the_20user_20interface_20strong_21',['&lt;strong&gt;B. Python API (The User Interface)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md92',1,'']]],
  ['apply_22',['apply',['../classPeriodicBoundary.html#ad1ac4291a92b159e061fc99e7777d34b',1,'PeriodicBoundary::apply()'],['../classBoundaryCondition.html#a89c213d7d45fd7fdaed4021a030ea998',1,'BoundaryCondition::apply()'],['../classAbsorbingBoundary.html#a5338d859c3ed9140e3b202156f645726',1,'AbsorbingBoundary::apply()']]],
  ['architectural_20requirements_20strong_23',['&lt;strong&gt;4. System &amp; Architectural Requirements&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md98',1,'']]],
  ['architecture_5fid_24',['ARCHITECTURE_ID',['../CMakeCXXCompilerId_8cpp.html#aba35d0d200deaeb06aee95ca297acb28',1,'CMakeCXXCompilerId.cpp']]],
  ['arquitectura_20de_20dirac_5fsolver_25',['Diagramas UML para la Arquitectura de dirac_solver',['../md_planning_2ulm-diagrams.html',1,'']]],
  ['arquitectura_20y_20patrones_20de_20diseño_20de_20dirac_5fsolver_26',['Arquitectura y Patrones de Diseño de dirac_solver',['../md_planning_2design-pattern.html',1,'']]],
  ['attribution_27',['Attribution',['../md_CODE__OF__CONDUCT.html#autotoc_md11',1,'']]]
];
